Three/Areas/Admin/Controllers/NewsAdminController.cs
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Three.ActionFilters;
using Three.Areas.Admin.ViewModels.News;
using Three.Models;
using Three.Models.Cmind;
using Three.Repositories;
using Three.Utility.Cmind;

namespace Three.Areas.Admin.Controllers
{
    [Authorize]
    [ErrorHandleAdminActionFilter]
    public class NewsAdminController : BaseAdminController
    {
        private NewsRepository newsRepository = new NewsRepository();

        public ActionResult Index(NewsIndexView model)
        {
            var query = newsRepository.Query(model.Status, model.Title);
            model.DataList = Mapper.Map<IEnumerable<NewsIndexItemView>>(query);
            return View(model);
        }

        public ActionResult Edit(int id = 0)
        {
            var model = new NewsView();
            model.OnlineTime = DateTime.Now;
            if (id != 0)
            {
                var query = newsRepository.FindBy(id);
                model = Mapper.Map<NewsView>(query);
            }

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Edit(NewsView model, HttpPostedFileBase file)
        {
            var hasFile = ImageHelper.CheckFileExists(file);

            if (ModelState.IsValid)
            {
                News news = Mapper.Map<News>(model);

                if (hasFile)
                {
                    ImageHelper.DeletePhoto(PhotoFolder, news.MainImage);
                    news.MainImage = ImageHelper.SaveImage(file, PhotoFolder);
                }

                int adminId = AdminInfoHelper.GetAdminInfo().ID;
                news.Updater = adminId;

                if (model.ID == 0)
                {
                    news.Creater = adminId;
                    model.ID = newsRepository.Insert(news);
                    ShowMessage(true, "新增成功");
                }
                else
                {
                    newsRepository.Update(news);
                    ShowMessage(true, "修改成功");
                }
                return RedirectToAction("Edit", new { id = model.ID });
            }

            return View(model);
        }

        public ActionResult Delete(int id)
        {
            DeleteImage(id);
            newsRepository.Delete(id);
            ShowMessage(true, "刪除成功");
            return RedirectToAction("Index");
        }

        public ActionResult DeleteImage(int id)
        {
            string image = newsRepository.DeleteImage(id);
            ImageHelper.DeletePhoto(PhotoFolder, image);
            ShowMessage(true, "刪除圖片成功");
            return RedirectToAction("Edit", new { id = id });
        }

        /// <summary>
        /// html編輯器圖片上傳
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult UploadPicture(HttpPostedFileBase upload, string CKEditorFuncNum, string CKEditor, string langCode)
        {
            string result = "";
            if (upload != null && upload.ContentLength > 0)
            {
                //儲存圖片至Server
                upload.SaveAs(Server.MapPath("~/FileUploads/ImagePhoto/" + upload.FileName));


                var imageUrl = Url.Content("~/FileUploads/ImagePhoto/" + upload.FileName);

                var vMessage = string.Empty;

                result = @"<html><body><script>window.parent.CKEDITOR.tools.callFunction(" + CKEditorFuncNum + ", \"" + imageUrl + "\", \"" + vMessage + "\");</script></body></html>";

            }
            return Content(result);
        }
    }
}

Three/Areas/Admin/Views/NewsAdmin/Edit.cshtml
@model Three.Areas.Admin.ViewModels.News.NewsView
@{
    ViewBag.Title = "Edit";
    string title = Model.ID == 0 ? "新增最新消息" : "編輯最新消息";
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        最新消息管理
    </h1>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">@title</h3>
                </div>

                @using (Html.BeginForm("Edit", "NewsAdmin", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.ID)

                    <div class="box-body">
                        <div class="nav-tabs-custom">
                            <div class="tab-content">
                                <div class="tab-pane active" id="tab_0">
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Title)
                                        @Html.TextBoxFor(model => model.Title, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.SubTitle)
                                        @Html.TextBoxFor(model => model.SubTitle, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.SubTitle, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Content)
                                        @Html.TextAreaFor(model => model.Content)
                                        @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.MainImage)
                                        <input type="file" id="photo_file" name="file" accept="image/x-png,image/jpeg">
                                        <p class="help-block">請上傳不超過3MB的圖片，建議尺寸(高965 x 寬1424 px,jpg檔)</p>
                                        @Html.ValidationMessageFor(model => model.MainImage, "", new { @class = "text-danger" })
                                        @if (!string.IsNullOrEmpty(Model.MainImage))
                                        {
                                            <img src="~/FileUploads/NewsPhoto/@Model.MainImage" class="img-thumbnail" style="width:400px" />
                                            @Html.HiddenFor(model => model.MainImage)
                                            <br />
                                            @Html.ActionLink("刪除圖片", "DeleteImage", "NewsAdmin", new { id = Model.ID }, new { @class = "btn btn-danger js-delete-confirm" })
                                        }
                                    </div>
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.OnlineTime)
                                        @Html.TextBoxFor(model => model.OnlineTime, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.OnlineTime, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="form-check">
                                        @Html.CheckBoxFor(model => model.Status, new { @class = "form-check-input" })
                                        <label class="form-check-label" for="check-box-status">
                                            @Html.DisplayNameFor(model => model.Status)
                                        </label>
                                    </div>
                                </div>
                                <!-- /.tab-pane -->
                            </div>
                            <!-- /.tab-content -->
                        </div>
                        <!-- nav-tabs-custom -->
                    </div>

                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">儲存</button>
                        @Html.ActionLink("刪除本篇文章", "Delete", new { id = Model.ID }, new { @class = "btn btn-danger js-delete-confirm" })
                        @Html.ActionLink("取消/回列表", "Index", null, new { @class = "btn btn-default" })
                    </div>
                }
            </div>
        </div>
    </div>
</section>

@section scripts{
    <script src="~/Scripts/ckeditor/ckeditor.js"></script>
    <script src="~/Scripts/Admin/fileUpload.js"></script>
    <script>
        $(function () {
            //ckeditor初始化
            var config = { width: '750px', filebrowserImageUploadUrl: '/NewsAdmin/UploadPicture' };
            CKEDITOR.editor.replace(
                'Content',
                config
            );
        })
    </script>

    <!--DatePicker-->
    <link rel="stylesheet" href="//apps.bdimg.com/libs/jqueryui/1.10.4/css/jquery-ui.min.css">
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script type="text/javascript">
        $(function () {
            $("#OnlineTime").datepicker({
                dateFormat: "yy/mm/dd"
            });
        });
    </script>
}

Three/Areas/Admin/Views/NewsAdmin/Index.cshtml
@model Three.Areas.Admin.ViewModels.News.NewsIndexView

<section class="content-header">
    <h1>
        最新消息管理
    </h1>
</section>

<section class="content">
    <div class="row">
        <!--搜尋條件-->
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">搜尋</h3>
                </div>
                @using (Html.BeginForm("Index", "NewsAdmin", FormMethod.Get, new { @class = "form-horizontal" }))
                {
                    <div class="box-body">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Title, new { @class = "col-sm-2 control-label" })
                            <div class="col-sm-10">
                                @Html.TextBoxFor(model => model.Title, new { @class = "form-control", @id = "inputTitle", @placeholder = "標題或副標題" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Status, new { @class = "col-sm-2 control-label" })
                            <div class="col-sm-10">
                                @Html.DropDownListFor(x => x.Status, Model.StatusOptions, new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-info">搜尋</button>
                                @Html.ActionLink("新增最新消息", "Edit", new { }, new { @class = "btn btn-primary" })
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>

        <!--清單-->
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">最新消息清單</h3>
                </div>
                <div class="box-body">
                    <table id="dataList" class="table table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(x => x.ID)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(x => x.Title)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(x => x.SubTitle)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(x => x.Status)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(x => x.OnlineTime)
                                </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                                @foreach (var item in Model.DataList)
                                {
                                    var statusStyle = item.Status ? "label-success" : "label label-danger";
                                    var statusDisplay = item.Status ? "啟用" : "停用";
                            <tr>
                                <td>
                                    @item.ID
                                </td>
                                <td>
                                    @item.Title
                                </td>
                                <td>
                                    @item.SubTitle
                                </td>
                                <td>
                                    <span class="label @statusStyle">@statusDisplay</span>
                                </td>
                                <td>
                                    @item.OnlineTime.ToShortDateString()
                                </td>
                                <td>
                                    @Html.ActionLink("編輯", "Edit", new { id = item.ID }, new { @class = "btn btn-primary" })
                                    @Html.ActionLink("刪除", "Delete", new { id = item.ID }, new { @class = "btn btn-danger js-delete-confirm" })
                                </td>
                            </tr>
                                }
                        </tbody>
                        <tfoot>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(x => x.ID)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(x => x.Title)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(x => x.SubTitle)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(x => x.Status)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(x => x.OnlineTime)
                                </th>
                                <th></th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>
@section scripts{
    <script>
        $(function () {
            $('#dataList').DataTable({
                'paging': true,
                'lengthChange': true,
                'searching': false,
                'ordering': true,
                'order': [[4, 'desc']],
                'info': true,
                'autoWidth': false
            });
        })
    </script>
}