Three/Controllers/NewsController.cs
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Three.ActionFilters;
using Three.Models;
using Three.Models.Cmind;
using Three.Repositories;
using Three.Utility.Cmind;
using Three.ViewModels.News;

namespace Three.Controllers
{
    [ErrorHandleActionFilter]
    public class NewsController : Controller
    {
        private NewsRepository newsRepository = new NewsRepository();

        public ActionResult Index(NewsIndexView model)
        {
            var query = newsRepository.List();
            model.PageSize = 6;
            var pageResult = query.ToPageResult<News>(model);
            model.PageResult = Mapper.Map<PageResult<NewsView>>(pageResult);
            return View(model);
        }

        public ActionResult Detail(int id = 0)
        {
            NewsView model = new NewsView();
            if (id != 0)
            {
                var query = newsRepository.FindBy(id);
                model = Mapper.Map<NewsView>(query);
            }
            return View(model);
        }
        /// <summary>
        /// 相關新聞
        /// </summary>
        /// <returns></returns>
        [ChildActionOnly]
        public ActionResult _News()
        {
            var query = newsRepository.List().Take(4);
            var model = Mapper.Map<IEnumerable<NewsView>>(query);
            return PartialView(model);
        }
    }
}

Three/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>三一越家物業管理顧問有限公司</title>
    <link rel="shortcut icon" href="~/favicon.ico" />
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.css" rel="stylesheet" type="text/css">
    <link href="~/Content/css/icons.css" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="~/Content/css/easy-responsive-tabs.css " />
    <link rel="stylesheet" type="text/css" href="~/Content/css/flexslider.css " />
    <link rel="stylesheet" type="text/css" href="~/Content/css/owl.carousel.css">
    <link rel="stylesheet" type="text/css" href="~/Content/css/jquery.fancybox.min.css">
    <!--[if lt IE 8]><!-->
    <link rel="stylesheet" href="~/Content/css/ie7/ie7.css">
    <!--<![endif]-->
    <link href="~/Content/css/style.css" rel="stylesheet" type="text/css">
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    @RenderSection("head", required: false)
</head>

<body data-spy="scroll" data-target=".navbar-fixed-top">
    <header>

        <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
            <div class="container">

                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                        <i class="fa fa-bars"></i>
                    </button>
                    <a class="navbar-brand" href="@Url.Action("Index","Home")">
                        三一越家物業管理顧問有限公司
                    </a>
                </div>
                <div class="collapse navbar-collapse navbar-main-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li style="padding-top: 15px;">
                            <a href="@Url.Action("Search","Project")"><i class="fa fa-search"></i></a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index","News")">
                                最新消息<br>
                                <span>NEWS</span>
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Service","Home")">
                                服務項目<br>
                                <span>SERVICE</span>
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("About","Home")">
                                公司簡介<br><span>ABOUT</span>
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index","Project")">
                                案例介紹<br>
                                <span>WORKS</span>
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Contact","Home")">
                                聯絡我們<br>
                                <span>CONTACT</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="clear"></div>

    @RenderBody()

    <div class="clear"></div>
    <footer>
        <div class="copyright">
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 col-md-6 col-lg-6">
                        Copyright &copy; 2019 31yuejia
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-hover-dropdown/2.2.1/bootstrap-hover-dropdown.min.js"></script>
    <script src="~/Content/js/custom.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

Three/Views/Shared/_Page.cshtml
@model Three.Models.Cmind.Page
@{
    var prePageDisable = Model.CurrentPage == 1;
    var prePageDisableCss = prePageDisable ? "<span>Previous</span>" : null;
    var prePage = (Model.CurrentPage - 1);

    var nextPageDisable = Model.CurrentPage == Model.TotalPages;
    var nextPageDisableCss = nextPageDisable ? "<span>Next</span>" : null;
    var nextPage = (Model.CurrentPage + 1);

    var currentPage = Model.CurrentPage;
}

@if (Model.TotalPages != 0)
{
    <div class="col-sm-12">
        <div>
            <ul class="pagination ins-page">
                @if (prePageDisableCss != null)
                {

                    <li class="active">
                        @Html.Raw(prePageDisableCss)
                    </li>
                }
                else
                {
                    <li>
                        <a href="?CurrentPage=@prePage" data-pager="@prePage" style="border-radius:20px">Previous</a>
                    </li>
                }
                
                @for (int i = 1; i <= Model.TotalPages; i++)
                {
                    var currentPageActive = (i == currentPage) ? "active" : null;
                    var stylecss = String.IsNullOrEmpty(currentPageActive) ? "" : "border-radius:50px;margin-right:10px";

                    if (currentPageActive != null)
                    {
                        @*<li class="@currentPageActive" style="@stylecss"><a href="?CurrentPage=@i">@Model.CurrentPage</a></li>*@
                        <li><span style="@stylecss">@Model.CurrentPage</span></li>

                    }
                    else
                    {
                        <li><a href="?CurrentPage=@i">@i</a></li>
                    }
                }

                @if (nextPageDisableCss != null)
                {
                    <li class="active">
                        @Html.Raw(nextPageDisableCss)
                    </li>
                }
                else
                {
                    <li>
                        <a href="?CurrentPage=@nextPage" data-pager="@nextPage">Next</a>
                    </li>
                }
            </ul>
        </div>

    </div>
}