Three/Areas/Admin/Controllers/ProjectAdminController.cs
using AutoMapper;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Three.ActionFilters;
using Three.Areas.Admin.ViewModels.Project;
using Three.Models;
using Three.Repositories;
using Three.Utility.Cmind;
using static Three.Models.EnumClass;

namespace Three.Areas.Admin.Controllers
{
    [Authorize]
    [ErrorHandleAdminActionFilter]
    public class ProjectAdminController : BaseAdminController
    {
        private ProjectRepository projectRepository = new ProjectRepository();
        private ProjectTypeRepository projectTypeRepository = new ProjectTypeRepository();
        private readonly string fileUploads = System.Web.Configuration.WebConfigurationManager.AppSettings["FileUploads"];

        public ActionResult Index(ProjectIndexView model)
        {
            var query = projectRepository.Query(model.Status, model.Title, model.AreaID, model.Type);

            IEnumerable<ProjectIndexItemView> data = Mapper.Map<IEnumerable<ProjectIndexItemView>>(query);
            model.DataList = data;


            var TypeListOptions = GetTypeListItem();
            TypeListOptions.Insert(0, new SelectListItem { Text = "請選擇", Value = "" });
            model.TypeOptions = TypeListOptions;

            var AreaListOptions = GetAreaListItem();
            AreaListOptions.Insert(0, new SelectListItem { Text = "請選擇", Value = "" });
            model.AreaOptions = AreaListOptions;
            return View(model);
        }

        public ActionResult Edit(int id = 0)
        {
            var model = new ProjectView();
            if (id != 0)
            {
                model = Mapper.Map<ProjectView>(projectRepository.FindBy(id));
            }

            model.TypeList = GetTypeListItem();
            model.AreaList = GetAreaListItem();

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Edit(ProjectView model, HttpPostedFileBase file)
        {
            var hasFile = ImageHelper.CheckFileExists(file);

            if (ModelState.IsValid)
            {
                Models.Project project = Mapper.Map<Models.Project>(model);

                if (hasFile)
                {
                    ImageHelper.DeletePhoto(PhotoFolder, project.MainImage);
                    project.MainImage = ImageHelper.SaveImage(file, PhotoFolder);
                }

                int adminId = AdminInfoHelper.GetAdminInfo().ID;
                project.Updater = adminId;
               
                if (model.ID == 0)
                {
                    project.Creater = adminId;
                    if (model.Type == 2)
                    {
                        project.AreaID = 0;
                    }
                    model.ID = projectRepository.Insert(project);

                    ShowMessage(true, "新增成功");
                }
                else
                {
                    if (model.Type == 2)
                    {
                        project.AreaID = 0;
                    }
                    projectRepository.Update(project);
                    ShowMessage(true, "修改成功");
                }
                return RedirectToAction("Edit", new { id = model.ID });
            }
            model.TypeList = GetTypeListItem();
            model.AreaList = GetAreaListItem();

            return View(model);
        }

        public ActionResult Delete(int id)
        {
            DeleteImage(id);

                #region 刪除banner資料表有該Projectid所有圖片
                var imageList = projectRepository.DeleteImageList(id);
                string savePath = Path.Combine(Server.MapPath(fileUploads), "BannerPhoto");
                foreach (var item in imageList)
                {
                    ImageHelper.DeletePhoto(savePath, item.ToString());
                }
                #endregion

            projectRepository.Delete(id);

            ShowMessage(true, "刪除成功");

            return RedirectToAction("Index");
        }

        public ActionResult DeleteImage(int id)
        {
            string image = projectRepository.DeleteImage(id);
            ImageHelper.DeletePhoto(PhotoFolder, image);
            ShowMessage(true, "刪除圖片成功");
            return RedirectToAction("Edit", new { id = id });
        }

        /// <summary>
        /// 案例分類清單
        /// </summary>
        /// <returns></returns>
        public List<SelectListItem> GetTypeListItem()
        {
            List<ProjectType> TypeList = projectTypeRepository.List().ToList();
            var result = new List<SelectListItem>();
            foreach (var item in TypeList)
            {
                result.Add(new SelectListItem()
                {
                    Text = item.Title,
                    Value = item.ID.ToString(),
                });
            }
            return result;
        }

        /// <summary>
        /// 案例區域清單
        /// </summary>
        /// <returns></returns>
        public List<SelectListItem> GetAreaListItem()
        {
            List<SelectListItem> areaList = new List<SelectListItem>();
            List<Area> AreaList = projectRepository.GetAllAreas().Where(a => a.Status == true).ToList();
            for (int i = 0; i < AreaList.Count; i++)
            {
                areaList.Add(new SelectListItem()
                {
                    Text = AreaList[i].Title,
                    Value = (AreaList[i].ID).ToString(),
                    Selected = false
                });
            }
                
            return areaList;
        }

        /// <summary>
        /// html編輯器圖片上傳
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult UploadPicture(HttpPostedFileBase upload, string CKEditorFuncNum, string CKEditor, string langCode)
        {
            string result = "";
            if (upload != null && upload.ContentLength > 0)
            {
                //儲存圖片至Server
                upload.SaveAs(Server.MapPath("~/FileUploads/ImagePhoto/" + upload.FileName));


                var imageUrl = Url.Content("~/FileUploads/ImagePhoto/" + upload.FileName);

                var vMessage = string.Empty;

                result = @"<html><body><script>window.parent.CKEDITOR.tools.callFunction(" + CKEditorFuncNum + ", \"" + imageUrl + "\", \"" + vMessage + "\");</script></body></html>";

            }
            return Content(result);
        }
    }
}

Three/Areas/Admin/Views/ProjectAdmin/Edit.cshtml
@model Three.Areas.Admin.ViewModels.Project.ProjectView
@{
    ViewBag.Title = "Edit";
    string title = Model.ID == 0 ? "新增案例" : "編輯案例";
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        案例管理
    </h1>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">@title</h3>
                </div>

                @using (Html.BeginForm("Edit", "ProjectAdmin", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.ID)

                    <div class="box-body">
                        <div class="nav-tabs-custom">
                            <div class="tab-content">
                                <div class="tab-pane active" id="tab_0">
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Title)
                                        @Html.TextBoxFor(model => model.Title, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.SubTitle)
                                        @Html.TextBoxFor(model => model.SubTitle, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.SubTitle, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Type)
                                        @Html.DropDownListFor(model => model.Type, Model.TypeList, new { @class = "form-control" })
                                    </div>
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.MainImage)
                                        <input type="file" id="photo_file" name="file" accept="image/x-png,image/jpeg">
                                        <p class="help-block">請上傳不超過3MB的圖片，建議尺寸(建議尺寸:高437 x 寬643 px, jpg檔)</p>
                                        @Html.ValidationMessageFor(model => model.MainImage, "", new { @class = "text-danger" })
                                        @if (!string.IsNullOrEmpty(Model.MainImage))
                                        {
                                            <img src="~/FileUploads/ProjectPhoto/@Model.MainImage" class="img-thumbnail" style="width:400px" />
                                            @Html.HiddenFor(model => model.MainImage)
                                            <br />
                                            @Html.ActionLink("刪除圖片", "DeleteImage", "ProjectAdmin", new { id = Model.ID }, new { @class = "btn btn-danger js-delete-confirm" })
                                        }
                                    </div>
                                    <div id="ProjectBannerAlert">
                                        <p style="color:green">儲存後可進行案例內容圖片管理</p>
                                    </div>
                                    <div id="ProjectBannerLink" class="hidden">
                                        <div class="form-group">
                                            <a href="@Url.Action("ProjectImage", "BannerAdmin", new { projectId = Model.ID} )" class="btn btn-default">案例分享圖片管理</a>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Content)
                                        @Html.TextAreaFor(model => model.Content, new { @class = "form-control", @style = "height:100px" })
                                        @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Sort)
                                        @Html.TextBoxFor(model => model.Sort, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.Sort, "", new { @class = "text-danger" })
                                    </div>

                                    <div id="ProjectDetail">
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.AreaID)
                                            @Html.DropDownListFor(model => model.AreaID, Model.AreaList, new { @class = "form-control" })
                                        </div>
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.Address)
                                            @Html.TextBoxFor(model => model.Address, new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                                        </div>
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.Link)
                                            @Html.TextBoxFor(model => model.Link, new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.Link, "", new { @class = "text-danger" })
                                        </div>
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.Footage)<p class="help-block">直接在坪數後面輸人單位</p>
                                            @Html.TextBoxFor(model => model.Footage, new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.Footage, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                    <div class="form-check">
                                        @Html.CheckBoxFor(model => model.Status, new { @class = "form-check-input" })
                                        <label class="form-check-label" for="check-box-status">
                                            @Html.DisplayNameFor(model => model.Status)
                                        </label>
                                    </div>
                                </div>
                                <!-- /.tab-pane -->
                            </div>
                            <!-- /.tab-content -->
                        </div>
                        <!-- nav-tabs-custom -->
                    </div>

                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">儲存</button>
                        @Html.ActionLink("刪除本篇案例", "Delete", "ProjectAdmin", new { id = Model.ID }, new { @class = "btn btn-danger js-delete-confirm" })
                        @Html.ActionLink("取消/回列表", "Index", "ProjectAdmin", null, new { @class = "btn btn-default" })
                    </div>
                }
            </div>
        </div>
    </div>
</section>

@section scripts{
    <script src="~/Scripts/ckeditor/ckeditor.js"></script>
    <script src="~/Scripts/Admin/fileUpload.js"></script>
    <script>
        $(function () {
            //ckeditor初始化
            var config = { width: '750px', filebrowserImageUploadUrl: '/ProjectAdmin/UploadPicture' };
            CKEDITOR.editor.replace(
                'Content',
                config
            );

            TypeDetail();
        });

        $('#Type').change(function () {
            TypeDetail();
        });

        function TypeDetail()
        {
            var Id = '@Model.ID';
            if (Id != '0')
            {
                $('#ProjectBannerLink').removeClass('hidden');
            }
            else
            {
                $('#ProjectBannerLink').addClass('hidden');
            }
            if ($('#Type').val() == '2')
            {
                $('#ProjectDetail').hide();
            }
            else
            {
                $('#ProjectDetail').show();
            }
        }
    </script>
}

Three/Areas/Admin/Views/ProjectAdmin/Index.cshtml
@model Three.Areas.Admin.ViewModels.Project.ProjectIndexView

<section class="content-header">
    <h1>
        案例管理
    </h1>
</section>

<section class="content">
    <div class="row">
        <!--搜尋條件-->
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">搜尋</h3>
                </div>
                @using (Html.BeginForm("Index", "ProjectAdmin", FormMethod.Get, new { @class = "form-horizontal" }))
                {
                <div class="box-body">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Title, new { @class = "col-sm-2 control-label" })
                        <div class="col-sm-10">
                            @Html.TextBoxFor(model => model.Title, new { @class = "form-control", @id = "inputTitle", @placeholder = "標題" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Type, new { @class = "col-sm-2 control-label" })
                        <div class="col-sm-10">
                            @Html.DropDownListFor(x => x.Type, Model.TypeOptions, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.AreaID, new { @class = "col-sm-2 control-label" })
                        <div class="col-sm-10">
                            @Html.DropDownListFor(x => x.AreaID, Model.AreaOptions, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Status, new { @class = "col-sm-2 control-label" })
                        <div class="col-sm-10">
                            @Html.DropDownListFor(x => x.Status, Model.StatusOptions, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-info">搜尋</button>
                            @Html.ActionLink("新增案例", "Edit", "ProjectAdmin", new { }, new { @class = "btn btn-primary" })
                        </div>
                    </div>
                </div>
                }
            </div>
        </div>

        <!--清單-->
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">案例清單</h3>
                </div>
                <div class="box-body">
                    <table id="dataList" class="table table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>@Html.DisplayNameFor(p => p.Title)</th>
                                <th>@Html.DisplayNameFor(p => p.Type)</th>
                                <th>@Html.DisplayNameFor(p => p.AreaID)</th>
                                <th>@Html.DisplayNameFor(p => p.Sort)</th>
                                <th>@Html.DisplayNameFor(p => p.Status)</th>
                                <th>@Html.DisplayNameFor(p => p.UpdateTime)</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.DataList)
                            {
                                var statusStyle = item.Status ? "label-success" : "label label-danger";
                                var statusDisplay = item.Status ? "啟用" : "停用";
                                var area_name = item.AreaID == 0 ? "無" : Model.AreaOptions[item.AreaID].Text;
                                <tr>
                                    <td>@item.Title</td>
                                    <td>@Model.TypeOptions[Convert.ToInt32(item.Type)].Text</td>
                                    <td>@area_name</td>
                                    <td>@item.Sort</td>
                                    <td>
                                        <span class="label @statusStyle">@statusDisplay</span>
                                    </td>
                                    <td>@item.UpdateTime</td>

                                    <td>
                                        @Html.ActionLink("編輯", "Edit", "ProjectAdmin", new { id = item.ID }, new { @class = "btn btn-primary" })
                                        @Html.ActionLink("刪除", "Delete", "ProjectAdmin", new { id = item.ID }, new { @class = "btn btn-danger js-delete-confirm" })
                                    </td>
                                </tr>
                            }
                        </tbody>
                        <tfoot>
                            <tr>
                                <th>@Html.DisplayNameFor(p => p.Title)</th>
                                <th>@Html.DisplayNameFor(p => p.Type)</th>
                                <th>@Html.DisplayNameFor(p => p.AreaID)</th>
                                <th>@Html.DisplayNameFor(p => p.Sort)</th>
                                <th>@Html.DisplayNameFor(p => p.Status)</th>
                                <th>@Html.DisplayNameFor(p => p.UpdateTime)</th>
                                <th></th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>
@section scripts{
    <script>
        $(function () {
            $('#dataList').DataTable({
                'paging': true,
                'lengthChange': true,
                'searching': false,
                'ordering': true,
                'order': [[3, 'asc']],
                'info': true,
                'autoWidth': false
            });
        })

    </script>
}